(() => {
  const $=s=>document.querySelector(s), state=window.CHROSYS_STATE;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const category=v=>window.CHROSYS_CATEGORIES[v]||String(v||'').toUpperCase(), risk=v=>v==='experimental'?'EXPERIMENTAL':v==='restricted'?'RESTRICTED':'DIAGNOSTIC';
  const all=()=>window.CHROSYS_FUNCTIONS.concat(state.imported.filter(x=>x&&!window.CHROSYS_FUNCTIONS.some(b=>b.url===x.url)).map(x=>({...x,imported:true}))), find=url=>all().find(x=>x.url===url), compatible=x=>!x.platforms||x.platforms.includes(state.platform);
  let statusTimer=null,deferredInstall=null;const status=t=>{$('#status').textContent=t;$('#status').hidden=false;clearTimeout(statusTimer);statusTimer=setTimeout(()=>$('#status').hidden=true,2600)};window.addEventListener('chrosys:status',e=>status(e.detail));
  const renderCategories=()=>{$('#sector').innerHTML='<option value="all">ALL SECTORS</option>'+Object.entries(window.CHROSYS_CATEGORIES).map(([k,v])=>`<option value="${esc(k)}">${esc(v)}</option>`).join('')};
  const render=()=>{const q=$('#search').value.trim().toLowerCase(),sector=$('#sector').value;let list=all();if(window.CHROSYS_VIEW==='favorites')list=list.filter(x=>state.favorites.has(x.url));if(window.CHROSYS_VIEW==='recent')list=list.filter(x=>state.recent.includes(x.url)).sort((a,b)=>state.recent.indexOf(a.url)-state.recent.indexOf(b.url));if(sector!=='all')list=list.filter(x=>x.category===sector);if(q)list=list.filter(x=>`${x.name} ${x.url} ${x.description} ${x.category}`.toLowerCase().includes(q));$('#count').textContent=`${list.length} SHOWN // ${all().length} REGISTERED // ${all().filter(x=>x.risk==='restricted').length} RESTRICTED`;$('#platform').textContent=state.platform.toUpperCase();$('#matrix').innerHTML=list.length?list.map((x,i)=>`<article class="card" data-risk="${esc(x.risk)}"><div class="card-top"><span>${String(i+1).padStart(2,'0')} // ${esc(category(x.category))}</span><button class="btn" style="min-height:30px;padding:4px 8px" data-favorite="${encodeURIComponent(x.url)}" aria-label="${state.favorites.has(x.url)?'Remove from':'Add to'} favorites">${state.favorites.has(x.url)?'★':'☆'}</button></div><h2>${esc(x.name)}</h2><code>${esc(x.url)}</code><p>${esc(x.description)}</p><div class="badges"><span class="badge">${esc(state.platform.toUpperCase())}</span><span class="badge ${x.risk==='restricted'?'red':x.risk==='experimental'?'amber':''}">${risk(x.risk)}</span></div><div class="card-actions"><button class="btn primary" data-start="${encodeURIComponent(x.url)}">INSPECT</button><button class="btn" data-info="${encodeURIComponent(x.url)}">DETAILS</button></div></article>`).join(''):'<div class="empty"><strong>NO FUNCTIONS MATCH</strong>Adjust the search or sector.</div>';$('#platformSelect').value=state.platform;$('#remember').textContent=`REMEMBER: ${state.remember?'ON':'OFF'}`;$('#remember').setAttribute('aria-pressed',state.remember)};
  const openTarget=x=>{if(!x)return;state.recent=[x.url,...state.recent.filter(u=>u!==x.url)].slice(0,8);window.CHROSYS_PERSIST();window.CHROSYS_TARGET.select(x)}, renderTarget=()=>{const x=window.CHROSYS_TARGET.current||find(state.selected);if(!x){$('#targetName').textContent='NO TARGET SELECTED';$('#targetUrl').textContent='—';return}$('#targetName').textContent=x.name;$('#targetUrl').textContent=x.url;$('#targetSector').textContent=category(x.category);$('#targetRisk').textContent=risk(x.risk);$('#targetPlatform').textContent=(x.platforms||[]).join(' / ').toUpperCase();$('#targetCompatibility').textContent=compatible(x)?'CATALOGUED':'PLATFORM MISMATCH';$('#targetDescription').textContent=x.description;$('#targetDetails').textContent=x.details;$('#handoffNotice').textContent='Direct navigation from a normal web page to privileged chrome:// or chrome-untrusted:// targets may be blocked by the browser. CHROSys reports the actual handoff result rather than simulating success'};
  window.addEventListener('chrosys:target',renderTarget);window.addEventListener('chrosys:route',()=>{if(state.route==='matrix')render();if(state.route==='target')renderTarget()});
  $('#matrix').addEventListener('click',e=>{const f=e.target.closest('[data-favorite]'),s=e.target.closest('[data-start]'),i=e.target.closest('[data-info]');if(f){const u=decodeURIComponent(f.dataset.favorite);state.favorites.has(u)?state.favorites.delete(u):state.favorites.add(u);window.CHROSYS_PERSIST();render();return}if(s)openTarget(find(decodeURIComponent(s.dataset.start)));if(i){const x=find(decodeURIComponent(i.dataset.info));if(x){$('#infoTitle').textContent=x.name;$('#infoText').textContent=x.details;$('#infoUrl').textContent=x.url;$('#info').hidden=false}}});
  $('#handoff').onclick=()=>window.CHROSYS_HANDOFF.attempt(window.CHROSYS_TARGET.current);$('#copy').onclick=()=>window.CHROSYS_HANDOFF.copy(window.CHROSYS_TARGET.current);$('#backMatrix').onclick=()=>window.CHROSYS_ROUTER.go('matrix');$('#search').oninput=()=>{window.CHROSYS_VIEW='all';render()};$('#sector').onchange=render;
  $('#platformSelect').onchange=e=>{state.platform=e.target.value;if(state.remember)window.CHROSYS_PERSIST();render();status(`TARGET // ${state.platform.toUpperCase()}`)};$('#remember').onclick=()=>{state.remember=!state.remember;window.CHROSYS_PERSIST();render()};document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>window.CHROSYS_ROUTER.go(b.dataset.route));
  $('#favorites').onclick=()=>{window.CHROSYS_VIEW='favorites';window.CHROSYS_ROUTER.go('matrix');render()};$('#recent').onclick=()=>{window.CHROSYS_VIEW='recent';window.CHROSYS_ROUTER.go('matrix');render()};$('#import').onclick=()=>window.CHROSYS_ROUTER.go('ingestion');$('#scan').onclick=()=>{const r=window.CHROSYS_IMPORT($('#importText').value);$('#importResult').textContent=`MATRIX SCAN COMPLETE\n\nFOUND: ${r.found}\nNEW: ${r.newCount}\nTOTAL LOCAL REGISTRY: ${r.total}`;$('#importResult').hidden=false;render();status(`MATRIX UPDATED // +${r.newCount}`)};
  const command=()=>{let input=$('#commandInput').value.trim();if(!input)return;const [cmd,...rest]=input.split(/\s+/),arg=rest.join(' ').toLowerCase();if(cmd==='clear'){window.CHROSYS_VIEW='all';$('#search').value='';render();return}if(cmd==='favorites'||cmd==='favs'){window.CHROSYS_VIEW='favorites';window.CHROSYS_ROUTER.go('matrix');render();return}if(cmd==='recent'){window.CHROSYS_VIEW='recent';window.CHROSYS_ROUTER.go('matrix');render();return}if(cmd==='open'||cmd==='info'){const x=find(arg)||all().find(v=>v.name.toLowerCase()===arg);if(!x){status('TARGET NOT FOUND');return}if(cmd==='open')openTarget(x);else{$('#infoTitle').textContent=x.name;$('#infoText').textContent=x.details;$('#infoUrl').textContent=x.url;$('#info').hidden=false}return}if(cmd==='category'){const k=Object.keys(window.CHROSYS_CATEGORIES).find(v=>v===arg||window.CHROSYS_CATEGORIES[v].toLowerCase()===arg);if(k){$('#sector').value=k;render()}else status('SECTOR NOT FOUND');return}if(cmd==='platform'){if(['desktop','android','webview'].includes(arg)){$('#platformSelect').value=arg;$('#platformSelect').dispatchEvent(new Event('change'))}else status('PLATFORM UNKNOWN');return}$('#search').value=input.replace(/^search\s+/i,'');window.CHROSYS_VIEW='all';render()};
  const init=()=>{if(!state.platform)state.platform=window.CHROSYS_PLATFORM.detect();const view=document.querySelector('[data-view="matrix"]'),head=view?.querySelector('.view-head');if(head&&!$('#commandInput')){const p=document.createElement('div');p.className='panel';p.style.marginBottom='12px';p.innerHTML='<div class="control-row"><span style="color:var(--green);align-self:center">&gt;</span><input class="field" id="commandInput" placeholder="open, info, category, platform, favorites, recent…" aria-label="Command input"><button class="btn primary" id="commandRun">RUN</button></div>';head.after(p);$('#commandInput').addEventListener('keydown',e=>{if(e.key==='Enter')command()});$('#commandRun').onclick=command}renderCategories();render();if(state.route==='target')renderTarget();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>status('OFFLINE SHELL UNAVAILABLE'))};
  $('#reset').onclick=()=>{localStorage.removeItem('chrosys.deck.v1');localStorage.removeItem('chrosys.deck.v2');location.reload()};$('#infoClose').onclick=()=>$('#info').hidden=true;$('#install').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#install').hidden=true}};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#install').hidden=false});window.addEventListener('appinstalled',()=>{deferredInstall=null;$('#install').hidden=true;status('PWA INSTALLED')});init();
})();